// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}
apply from: 'variables.gradle'
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.15.0'
            force 'androidx.activity:activity:1.9.3'
            force 'androidx.appcompat:appcompat:1.7.0'
            force 'androidx.fragment:fragment:1.8.5'
            force 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
            force 'androidx.webkit:webkit:1.12.1'
            force 'androidx.browser:browser:1.8.0'
        }
    }
    tasks.configureEach { task ->
        if (task.name.toLowerCase().contains('lint') || task.name.toLowerCase().contains('aarmetadata')) {
            task.enabled = false
        }
    }
}
gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.allTasks.each { task ->
        if (task.name.toLowerCase().contains('lint') || task.name.toLowerCase().contains('aarmetadata')) {
            task.enabled = false
        }
    }
}
task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
