name: Build Native Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        npm install --legacy-peer-deps
        npm install -D @capacitor/assets --legacy-peer-deps
        npm install @codetrix-studio/capacitor-google-auth --legacy-peer-deps

    - name: Initialize Android Platform
      run: |
        npx cap add android
        npx cap sync android
        npx @capacitor/assets generate --android

    - name: Inject Google Services JSON
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

    - name: Inject Native Client ID
      run: |
        cat <<EOF > android/app/src/main/res/values/google_auth_strings.xml
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="390279102837-u12a9h0n65uo9orbaa4h3j0anvleses9.apps.googleusercontent.com"</string>
        </resources>
        EOF

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Compile Unsigned Release APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Publish Raw APK Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{steps.sign_app.outputs.signedReleaseFile}}
        tag: "latest"
        name: "Crystal AI (Latest Build)"
        body: "Tap the .apk file below to install directly."
        allowUpdates: true
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
